name: tasky_app
description: A full-featured Tasky app
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and state
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  lottie: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.7.20

  # Notifications
  flutter_local_notifications: ^17.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_lints: ^3.0.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/splash_animation.json
    - assets/task1.png
    - assets/task2.png
    - assets/task3.png
    - assets/task4.png  
 

flutter_native_splash:
  color: "#ffffff"
  image: assets/Logo.png
  android: true
  ios: true
  web: false
