// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5zLsxO_sc6_WREnhva9SceVk3BXbpqc',
    appId: '1:189250337612:web:a732b3856d60a57a426de9',
    messagingSenderId: '189250337612',
    projectId: 'tasky-app-f47f9',
    authDomain: 'tasky-app-f47f9.firebaseapp.com',
    storageBucket: 'tasky-app-f47f9.firebasestorage.app',
    measurementId: 'G-MVCBW8EPGV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-PO92-u6Da28Kof1r3HgOC9F5TK2wJM',
    appId: '1:189250337612:ios:e7aa91b94a93f26a426de9',
    messagingSenderId: '189250337612',
    projectId: 'tasky-app-f47f9',
    storageBucket: 'tasky-app-f47f9.firebasestorage.app',
    iosClientId: '189250337612-v23oemqgc7lknjhqoubn6t741pg6fnr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-PO92-u6Da28Kof1r3HgOC9F5TK2wJM',
    appId: '1:189250337612:ios:e7aa91b94a93f26a426de9',
    messagingSenderId: '189250337612',
    projectId: 'tasky-app-f47f9',
    storageBucket: 'tasky-app-f47f9.firebasestorage.app',
    iosClientId: '189250337612-v23oemqgc7lknjhqoubn6t741pg6fnr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc5zLsxO_sc6_WREnhva9SceVk3BXbpqc',
    appId: '1:189250337612:web:afb8f751d9b5674b426de9',
    messagingSenderId: '189250337612',
    projectId: 'tasky-app-f47f9',
    authDomain: 'tasky-app-f47f9.firebaseapp.com',
    storageBucket: 'tasky-app-f47f9.firebasestorage.app',
    measurementId: 'G-H2F31E7S32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtv_B6TAbVfiBO_X8X35tD851nBWDNX0c',
    appId: '1:189250337612:android:d88cc8014abc8238426de9',
    messagingSenderId: '189250337612',
    projectId: 'tasky-app-f47f9',
    storageBucket: 'tasky-app-f47f9.firebasestorage.app',
  );

}